name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install gem bundle
      run: bundle install
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
